### ISSUE TITLE
Qt not bundled correctly

### ISSUE THREAD

**Issue by probonopd** [azubieta/appimage-info#2]
Reference:
https://github.com/AppImage/appimage.github.io/blob/71efc41266965e5419e40a03d3952e2f234fe2dc/database/appimage-releases-indexer/screenshot.png

![](https://github.com/AppImage/appimage.github.io/blob/71efc41266965e5419e40a03d3952e2f234fe2dc/database/appimage-releases-indexer/screenshot.png?raw=true)

**Comment by azubieta** [comment]
We should blame the new @TheAssassin linux-deploy-plugin-qt for this.

**Comment by TheAssassin** [comment]
Looking into this right now. Feel free to create issues in the plugin's issue tracker.

**Comment by TheAssassin** [comment]
The qt plugin wasn't run at all here. Not my fault.

**Comment by TheAssassin** [comment]
Fix available in #3.

**Comment by azubieta** [comment]
Qt will be no longer a requirement.

**Comment by azubieta** [comment]
Qt will be no longer a requirement.
