### ISSUE TITLE
.zsync file is missing on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [azubieta/appimage-info#6]
`.zsync file is missing on GitHub Releases for AppImageUpdate` file is missing on GitHub Releases for AppImageUpdate. linuxdeployqt used to produce one automagically...

**Comment by probonopd** [comment]
I hope this will automatically be fixed once https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/commit/b5a951c491ad3e9899a488e490fbab0439c41122 builds which is currently blocked by https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/issues/1.

**Comment by azubieta** [comment]
Your prayers were heard. Now linuxdeploy-plugin-appimage makes .zsync files and we are able to provide them.

**Comment by TheAssassin** [comment]
You could've always `UPD_INFO=xxxx ./linuxdeploy-x86_64.AppImage --output appimage <...>`.
